### ISSUE TITLE
Crafting 2 or more Berry Crates at once causes a huge amount of stacks of Sweet Berries to spawn and drop from the player

### ISSUE THREAD

**Issue by megatrook** [axperty/cratedelight-fabric#4]
https://github.com/axperty/cratedelight-fabric/assets/77197776/adf90279-f29c-4020-9a0b-807f7f9b9af4

this is maybe one of the funniest bugs i've seen, i have no idea what's happening here, but it seems to happen only when i craft 3 or more Berry Crates at once. as i show in the video, it doesnt seem to happen for any other items, including presumably simillar crates from this same mod

**Comment by axperty** [comment]
Hi megatrook,

I'll look into it right now, this is the weirdest bug I've ever seen. I'll keep you updated.
Thanks for reporting this bug.

Have a good day, and don't craft too many berry crates for now.
Axperty

**Comment by axperty** [comment]
Hi megatrook,

After doing some testing, I tried crafting multiple stacks of sweet berries at the same time to make a berry crate, and everything worked as expected. 
I took a look at the recipe itself, but I saw nothing that could cause roblems when crafting.

The problem might be caused by another mod.  I still recommend updating to the latest version of Crate Delight released today, just in case, and try to test if this happens again.

If you can provide a list of what mods you're using so I can investigate further to solve this problem I would appreciate it.
Please keep me updated on this, I'm going to test one more time.

Have a good day,
Axperty.

**Comment by megatrook** [comment]
Hi axperty,

Thank you for your swift replies. I did a little bit of testing, and I believe to have found what is causing this issue. I have another mod installed called "Golden Delicacies", which, among other things, also adds crates of different kinds, like Berries, Carrots, Apples, etc. - I used "Item Obliterator" to disable them, thus only allowing Crate Delight's crates to be crafted. However, having these crates disabled this way seems to be precisely what causes this bug. 

From my testing, I've found that this bug happens when crafting crates of: Sweet Berries, Apples, Glow Berries, Potatoes, and Beetroot. These are all crates that exist in both mods, but oddly enough, the bug doesn't happen with Carrots, despite it also being present in both.
I also have a correction: it happens when crafting 2 or more crates at once.

Here's my full mod list, as requested, in case it is useful: https://mclo.gs/ecD19N7
I'm running Fabric 1.20.1. I also have Polymorph installed, or else the crate recipes don't show up when disabled.

I guess I'll be sending a bug report to Item Obliterator, since it seems to be the cause of this problem.
For now, I'll disable Golden Delicacies on that instance, to avoid these issues.

Thank you for your attention. 
Have a lovely day!
megatrook

**Comment by axperty** [comment]
Hi megatrook,

I'm glad everything worked and you found what was causing the problem. And thank you for using Crate Delight, it will be receiving more updates in the future.

If you ever have other issues with Crate Delight, please don't forget to submit your issue.

Have a good day,
Axperty.
